name: CI

on:
  push:
    branches: 
      - master
      - dev
    paths: 
      - 'api/***'
  pull_request:
    branches: 
      - master
      - dev
    paths: 
      - 'api/***'

jobs:
  test:
    if: ${{ steps.abc.outputs.all }}
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10.x, 12.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}        
        
      - name: Change to API directory
        run: cd ./api
        
      - name: Install clean project
        run: npm ci
        
      - name: Create code build
        run: npm run build --if-present
        
      - name: Run eslint
        run: yarn run eslint
        
      - name: Run Tests
        run: npm test
