name: API Test

on:
  workflow_dispatch: 
    inputs:
      LogLevel:
        description: 'Log level'
        required: true
        default: 'Test Workflow'
      tags:
        description: 'Trigger Test Workflow'
  push:
    branches: 
      - master
    paths: 
      - 'api/**'
  pull_request:
    branches: 
      - master
    paths: 
      - 'api/**'

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }} 
        
      - name: Install clean project
        working-directory: ./api     
        run: npm ci
        
      - name: Create code build
        working-directory: ./api     
        run: npm run build --if-present
      
      - name: Install eslint
        working-directory: ./api
        run: yarn add eslint
        
      - name: Run eslint
        working-directory: ./api     
        run: yarn run eslint
        
      - name: Run Tests
        working-directory: ./api     
        run: npm test
